
env: LOCAL

db:
  url: postgresql://food_tinder:secret@localhost:5432/food_tinder?sslmode=disable
  maxidletime: 1h
  maxlifetime: 1h
  maxopenconn: 100
  maxidleconn: 10

mongo_url: 123

feed_url: https://amperoid.tenants.foodji.io/machines/4bf115ee-303a-4089-a3ea-f6e7aae0ab94

http_port: ":9000"

migration:
  direction: "up"
  version: 0