
env: LOCAL

db:
  url: postgresql://postgres:password@localhost:5432/foodtinder?sslmode=disable
  maxidletime: 1h
  maxlifetime: 1h
  maxopenconn: 100
  maxidleconn: 10

mongo_url: mongodb://localhost:27017

feed_url: https://amperoid.tenants.foodji.io/machines/4bf115ee-303a-4089-a3ea-f6e7aae0ab94

http_port: ":9000"

migration:
  direction: "up"
  version: 0

worker:
  minute: "0"
  hour: "0"
  day: "*"
  month: "*"
  dayofweek: "*"